### cards Index
GET http://localhost:3000/cards.json

### cards reset
PATCH http://localhost:3000/cards.json

### cards Create
POST http://localhost:3000/cards.json
Content-Type: application/json

{
"name": "Test name",
"width": 640,
"height": 480
}

### cards Show
GET http://localhost:3000/cards/73.json
Content-Type: application/json

### cards Update
PATCH http://localhost:3000/cards/1.json
Content-Type: application/json

# {
# "name": "New name",
# "width": 320,
# "height": 240
# }

### cards Destroy
DELETE http://localhost:3000/cards/165.json




### decks Index
GET http://localhost:3000/decks.json

### decks Create
POST http://localhost:3000/decks.json
Content-Type: application/json

# {
# "name": "Test name",
# "width": 640,
# "height": 480
# }

### decks Show
GET http://localhost:3000/decks/1.json

### decks draw(update)
PATCH http://localhost:3000/decks/1.json
Content-Type: application/json

{
"is_active": true,
"is_hand": true

}

### decks Destroy
DELETE http://localhost:3000/decks/1.json

### Hand SHOW
GET http://localhost:3000/hands/1.json

# ### hands Create
# POST http://localhost:3000/hands.json
# Content-Type: application/json

# {
# "open_str": "Test Hand",
# "open_int": 1
# }

### hands play(update)
PATCH http://localhost:3000/hands/1.json
Content-Type: application/json

# {
# "is_active": true,
# "is_hand": true

# }

### stack SHOW
GET http://localhost:3000/stacks/1.json

### stacks play(update)
PATCH http://localhost:3000/stacks/1.json
Content-Type: application/json

### battlefeild SHOW
GET http://localhost:3000/battlefeilds/1.json

### battlefeilds play(update)
PATCH http://localhost:3000/battlefeilds/1.json
Content-Type: application/json

### graveyard SHOW
GET http://localhost:3000/graveyards/1.json

### graveyards play(update)
PATCH http://localhost:3000/graveyards/1.json
Content-Type: application/json

### exile SHOW
GET http://localhost:3000/exiles/1.json

### exile Create
POST http://localhost:3000/exiles.json

### graveyard Create
POST http://localhost:3000/graveyards.json

### battlefeild Create
POST http://localhost:3000/battlefeilds.json

### land Create
POST http://localhost:3000/lands.json

### hand Create
POST http://localhost:3000/hands.json

### stack Create
POST http://localhost:3000/stacks.json